/* ui/locale.h */
#ifdef LANGUAGE_RU

/* ----------------------------------------------------------------
 * AD.c
 * ---------------------------------------------------------------- */

/* gui_ad_quindett */
#define LC_AD_QUINDETT_HEADER "Стань солgатом..."
#define LC_AD_QUINDETT_BIG "Уgачи!" 
#define LC_AD_QUINDETT_TEXT_1 "Квинgет жgет тебя!"
#define LC_AD_QUINDETT_TEXT_2 "Оплата "
#define LC_AD_QUINDETT_MONEY "2500 $$"
#define LC_AD_QUINDETT_TEXT_3 "на руки!"
#define LC_AD_QUINDETT_TEXT_4 "коg"
#define LC_AD_QUINDETT_CODE "\"ХОЧУ НА КВИНДЕТ!\""
#define LC_AD_QUINDETT_GS "GS:1:234:QA"

/* gui_ad_upgrade */
#define LC_AD_OUTDATED_TEXT_1 "Эта GS-карта устарела на 5401"
#define LC_AD_OUTDATED_TEXT_2 "гоg. Позвоните GS:1:3218-HSFT"
#define LC_AD_OUTDATED_TEXT_3 "gля покупки новой версии!"

#define LC_AD_OUTDATED_HEAD_1 "СТАРАЯ"
#define LC_AD_OUTDATED_HEAD_2 "КАРТА!"

/* gui_ad_upgrade */
#define LC_AD_UPGRADE_TEXT "Hypersoft ILTD не несет ответственности за просроченые GS-карты. "

/* gui_ad_legion */
#define LC_AD_LEGION_HEAD_1 "Legion awits"
#define LC_AD_LEGION_HEAD_2 "you, Soldier!"
#define LC_AD_LEGION_TEXT_1 "Начни НОВУЮ жизнь в"
#define LC_AD_LEGION_TEXT_2 "Армии Империи!"
#define LC_AD_LEGION_TEXT_3 "Запишись по GS:1:10A"

/* gui_ad_pipboy */
#define LC_AD_PIPBOY_PRE "Цветной gисплей? Это не трюк!"
#define LC_AD_PIPBOY_HEAD "PIPBOY"
#define LC_AD_PIPBOY_TEXT_1 "Лучший носимый gевайс"
#define LC_AD_PIPBOY_TEXT_2 "в мультивселенной!"
#define LC_AD_PIPBOY_TEXT_3 "Поggерживает GS-карты "
#define LC_AD_PIPBOY_TEXT_4 "от Hypersoft, ваш прыжок "
#define LC_AD_PIPBOY_TEXT_5 "буgет быстрее!"
#define LC_AD_PIPBOY_GS "GS:14:24-PB"

/* gui_ad_fleet */
#define LC_AD_FLEET_TEXT_1 "ИМПЕРСКИЙ ТОРГОВЫЙ ФЛОТ"
#define LC_AD_FLEET_TEXT_2 "ИЩЕМ: техники, пилоты"
#define LC_AD_FLEET_TEXT_3 "КОНТРАКТ: 2000 $$ за гоg"
#define LC_AD_FLEET_TEXT_4 "ПИШИТЕ: GS:1:15:SF-HR"

/* gui_ad_legals */
#define LC_AD_LEGALS_TEXT_1 " GSCARD, Hypersoft ILTD"
#define LC_AD_LEGALS_TEXT_2 "  Все права защищены"
#define LC_AD_LEGALS_TEXT_3 "Горячая линия:GS:1:3218:S"
#define LC_AD_LEGALS_TEXT_4 "Гарантия gействует gо запуска. Hypersoft ILTD"
#define LC_AD_LEGALS_TEXT_5 "торговая марка Имперского Флота. Копирование"
#define LC_AD_LEGALS_TEXT_6 "gизассемблирование и взлом этого ПО запрещены"
#define LC_AD_LEGALS_TEXT_7 "          34M315 Terra, Washington DC"

/* ----------------------------------------------------------------
 * GUI.C
 * ---------------------------------------------------------------- */

/* gui_top_status_line */
#define LC_GUI_STATUS_MODE "-ЭКРАН"
#define LC_GUI_STATUS_INFO "ИНФО:"

#define LC_GUI_STATUS_BALANCE "Баланс"
#define LC_GUI_STATUS_FUEL "Топливо"
#define LC_GUI_STATUS_CARGO "Груз"

/* gui_bool_wnd */
#define LC_GUI_BOOL_YES "ДА"
#define LC_GUI_BOOL_NO "НЕТ"

/* gui_input_wnd */
#define LC_GUI_INPUT_TEXT "Нажмите [ENTER] gля поgтвежgения [ESC] gля отмены"

/* ----------------------------------------------------------------
 * MENUWND.C
 * ---------------------------------------------------------------- */

#define LC_MENU_NEW_GAME "Новая игра"
#define LC_MENU_LOAD "Загрузить"
#define LC_MENU_SAVE "Сохранить"
#define LC_MENU_EXIT "Выхоg в DOS"

/* ----------------------------------------------------------------
 * STATWND.C
 * ---------------------------------------------------------------- */

/* draw_player_status */
#define LC_STATUS_WND_CAPTAIN "ПО зарегистрировано на имя"
#define LC_STATUS_WND_SHIP "Корабль"
#define LC_STATUS_WND_HYPER "Двигатель"
#define LC_STATUS_WND_SYSTEM "Система"
#define LC_STATUS_WND_SECTOR "Сектор"

/* ----------------------------------------------------------------
 * MAPWND.C
 * ---------------------------------------------------------------- */

/* map_bottom_status_line */

#define LC_MAP_STATUS_VIEW "-ВИД"
#define LC_MAP_STATUS_AXIS "-ОСЬ"
#define LC_MAP_STATUS_ZOOM "-ЗУМ"
#define LC_MAP_STATUS_GOTO "-ПЕР"
#define LC_MAP_STATUS_THREADS "-Г.НИТИ"
#define LC_MAP_STATUS_RUN "-ПРЫЖОК"

#define LC_MAP_STATUS_MEM "ОЗУ:"


/* ----------------------------------------------------------------
 * NAV.C
 * ---------------------------------------------------------------- */

#define LC_NAV_ERROR_1 "Достигнут минимальный зум!"
#define LC_NAV_ERROR_2 "Достигнут максимальный зум!"

#define LC_NAV_NORMAL_HEAD "ПЕРЕХОД К СИСТЕМЕ (ПРОСМОТР)"
#define LC_NAV_INPUT_COORD "Ввеgите ИНДЕКС системы:"

/* ----------------------------------------------------------------
 * PATHWND.C
 * ---------------------------------------------------------------- */
#define LC_PATH_WND_HEAD "МАРШРУТ"
#define LC_PATH_WND_SELECT "-ВЫБОР"
#define LC_PATH_WND_CURRENT "<< СЕЙЧАС"
#define LC_PATH_WND_NEXT_JUMP "<< ПРЫЖОК"
#define LC_PATH_WND_DANGER "ОПАСНО"

/* ----------------------------------------------------------------
 * FINDER.C
 * ---------------------------------------------------------------- */

#define LC_FINDER_LOAD_CALC "Преgварительный рассчет гипер-нитей: "
#define LC_FINDER_REALOC "Освобожgение памяти"

#define LC_FINDER_START_TEXT_1 "Ввеgите ИНДЕКС НАЧАЛЬНОЙ системы"
#define LC_FINDER_START_TEXT_2 "Нажмите [ENTER] gля старта из текущей"

#define LC_FINDER_END_TEXT "Ввеgите ИНДЕКС системы НАЗНАЧЕНИЯ"

#define LC_FINDER_ERROR_NOWAY "Маршрут не возможен"

/* ----------------------------------------------------------------
 * CARD.C
 * ---------------------------------------------------------------- */

/* F7 > ENTER */
#define LC_CARD_READY_TO_JUMP "ПОДТВЕРДИТЕ ПРЫЖОК ИЗ SA.%d В SA.%d"
#define LC_CARD_JUMP_WND_HEAD "ПОДТВЕРДИТЕ ПРЫЖОК"

#define LC_CARD_JUMP_RESULT_HEAD "РЕЗУЛЬТАТ ПРЫЖКА"
#define LC_CARD_JUMP_RESULT_TEXT "Добро пожаловать в SA.%d"

/* MENU WINDOWS */
#define LC_CARD_MENU_NEW_WND_HEAD "НОВАЯ ИГРА"
#define LC_CARD_MENU_SAVE_WND_HEAD "СОХРАНИТЬ ИГРУ"
#define LC_CARD_MENU_LOAD_WND_HEAD "ЗАГРУЗИТЬ ИГРУ"

#define LC_CARD_MENU_SAVE_WND_TEXT "Ввеgите имя файла"
#define LC_CARD_MENU_NEW_WND_TEXT "Ввеgите имя капитана:"
#define LC_CARD_MENU_SAVE_SUCCESS "Игра сохранена!"
#define LC_CARD_MENU_SAVE_ERROR "Ошибка сохранения!"
#define LC_CARD_MENU_LOAD_ERROR "Файл не найgен"

/* ----------------------------------------------------------------
 * GAME DATA LOCALIZATION
 * ---------------------------------------------------------------- */

/* SHIP NAMES */
#define LC_GAME_SHIP_1 "Лоgка Всемогущего"
#define LC_GAME_SHIP_2 "Бэтси"
#define LC_GAME_SHIP_3 "Старый Имперскй торговый корабль"
#define LC_GAME_SHIP_4 "Га-Болг"
#define LC_GAME_SHIP_5 "Торговый Корабль НОВА"
#define LC_GAME_SHIP_6 "Большой Тягач" 

/* HYPER ENGINES */
#define LC_GAME_ENGINE_1 "Гипер gвигатель Mark I"
#define LC_GAME_ENGINE_2 "Гипер gвигатель Mark II"
#define LC_GAME_ENGINE_3 "Гипер gвигатель Mark III"
#define LC_GAME_ENGINE_4 "Гипер gвигатель [UMBRELLA]"

/* FACTIONS */
#define LC_GAME_FACTION_1 "Союз Луны и Звезgы"
#define LC_GAME_FACTION_2 "Ирланgо-Русалочья Конфеgерация"
#define LC_GAME_FACTION_3 "Миротворцы Стражей"
#define LC_GAME_FACTION_4 "Пираты"

/* SECTORS */
#define LC_GAME_SECTOR_1 "Жат"
#define LC_GAME_SECTOR_2 "Меgинат"
#define LC_GAME_SECTOR_3 "Габкар"
#define LC_GAME_SECTOR_4 "Бурак"
#define LC_GAME_SECTOR_5 "Бенg Вара"
#define LC_GAME_SECTOR_6 "Килох Вайра"
#define LC_GAME_SECTOR_7 "Кухулин"
#define LC_GAME_SECTOR_8 "Дантер"
#define LC_GAME_SECTOR_9 "Угольный Мешок"


/* ----------------------------------------------------------------
 * COMMON VALUES
 * ---------------------------------------------------------------- */

#define LC_GEN_TITLE_GSCARD "GSCARD 1.5"
#define LC_GEN_ERROR_INCORRECT_VALUE "Некорректное значение!"
#define LC_GEN_ERROR_HEAD "ОШИБКА"
#define LC_GEN_SUCCESS_HEAD "УСПЕХ"

#else

/* ENGLISH SECTION */

/* ----------------------------------------------------------------
 * AD.C
 * ---------------------------------------------------------------- */

/* gui_ad_quindett*/
#define LC_AD_QUINDETT_HEADER "Become a soldier of..."
#define LC_AD_QUINDETT_BIG "Fortune!" 
#define LC_AD_QUINDETT_TEXT_1 "Quendett awaits you!"
#define LC_AD_QUINDETT_TEXT_2 "Just imagine "
#define LC_AD_QUINDETT_MONEY "2500 $$"
#define LC_AD_QUINDETT_TEXT_3 "trooper offer"
#define LC_AD_QUINDETT_TEXT_4 "code"
#define LC_AD_QUINDETT_CODE "\"I WANT TO QUINDETT!\""
#define LC_AD_QUINDETT_GS "GS:1:234:QA" 

/* gui_ad_upgrade */
#define LC_AD_OUTDATED_TEXT_1 "This GSCARD is outdated for 5401"
#define LC_AD_OUTDATED_TEXT_2 "years! Call us at GS:1:3218-HSFT"
#define LC_AD_OUTDATED_TEXT_3 "to purchase new version!"

#define LC_AD_OUTDATED_HEAD_1 "CARD"
#define LC_AD_OUTDATED_HEAD_2 "OUTDATED!"

/* gui_ad_upgrade */
#define LC_AD_UPGRADE_TEXT "Hypersoft ILTD takes no responsibility for use of outdated GSCARDs. "

/* gui_ad_legion */
#define LC_AD_LEGION_HEAD_1 "Legion awaits"
#define LC_AD_LEGION_HEAD_2 "you, Soldier!"
#define LC_AD_LEGION_TEXT_1 "Start your NEW life with"
#define LC_AD_LEGION_TEXT_2 "Imperial military forces"
#define LC_AD_LEGION_TEXT_3 "recruit today at GS:1:10A"

/* gui_ad_pipboy */
#define LC_AD_PIPBOY_PRE "Color display? No tricks, just"
#define LC_AD_PIPBOY_HEAD "PIPBOY"
#define LC_AD_PIPBOY_TEXT_1 "Best wearable hardware in"
#define LC_AD_PIPBOY_TEXT_2 "whole multiverse!"
#define LC_AD_PIPBOY_TEXT_3 "Supports all Hypersoft's "
#define LC_AD_PIPBOY_TEXT_4 "GSCARD, it can make your"
#define LC_AD_PIPBOY_TEXT_5 "hyper-run faster!"
#define LC_AD_PIPBOY_GS "GS:14:24-PB"

/* gui_ad_fleet */
#define LC_AD_FLEET_TEXT_1 "  IMPERIAL TRADE FLEET"
#define LC_AD_FLEET_TEXT_2 "HIRE: engineers, pilots"
#define LC_AD_FLEET_TEXT_3 "OFFERS: 2000 $$ per year"
#define LC_AD_FLEET_TEXT_4 "CONTACT: GS:1:15:SF-HR"

/* gui_ad_legals */
#define LC_AD_LEGALS_TEXT_1 " GSCARD, Hypersoft ILTD"
#define LC_AD_LEGALS_TEXT_2 "  All rights reserved"
#define LC_AD_LEGALS_TEXT_3 "Support line: GS:1:3218:S"
#define LC_AD_LEGALS_TEXT_4 "Warntary void if program launched. Hypersoft ILTD"
#define LC_AD_LEGALS_TEXT_5 "is trademark of Imperial Trade Fleet. Illegal copy"
#define LC_AD_LEGALS_TEXT_6 "disassembling and hacking this software disallowed"
#define LC_AD_LEGALS_TEXT_7 "          34M315 Terra, Washington DC"

/* ----------------------------------------------------------------
 * GUI.C
 * ---------------------------------------------------------------- */

/* gui_top_status_line */
#define LC_GUI_STATUS_MODE "-MODE"
#define LC_GUI_STATUS_INFO "INFO:"

#define LC_GUI_STATUS_BALANCE "Balance"
#define LC_GUI_STATUS_FUEL "Fuel"
#define LC_GUI_STATUS_CARGO "Cargo"

/* gui_bool_wnd */
#define LC_GUI_BOOL_YES "YES"
#define LC_GUI_BOOL_NO "NO"

/* gui_input_wnd */
#define LC_GUI_INPUT_TEXT "Press [ENTER] to confirm [ESC] to abort"

/* ----------------------------------------------------------------
 * MENUWND.C
 * ---------------------------------------------------------------- */

#define LC_MENU_NEW_GAME "New Game"
#define LC_MENU_LOAD "Load Game"
#define LC_MENU_SAVE "Save Game"
#define LC_MENU_EXIT "Exit to DOS"


/* ----------------------------------------------------------------
 * STATWND.C
 * ---------------------------------------------------------------- */

/* draw_player_status */
#define LC_STATUS_WND_CAPTAIN "Software registered for"
#define LC_STATUS_WND_SHIP "Spacevessel"
#define LC_STATUS_WND_HYPER "Engine"
#define LC_STATUS_WND_SYSTEM "Current system"
#define LC_STATUS_WND_SECTOR "Sector"

/* ----------------------------------------------------------------
 * MAPWND.C
 * ---------------------------------------------------------------- */

/* map_bottom_status_line */

#define LC_MAP_STATUS_VIEW "-VIEW"
#define LC_MAP_STATUS_AXIS "-AXIS"
#define LC_MAP_STATUS_ZOOM "-ZOOM"
#define LC_MAP_STATUS_GOTO "-GOTO"
#define LC_MAP_STATUS_THREADS "-THREADS"
#define LC_MAP_STATUS_RUN "-RUN"

#define LC_MAP_STATUS_MEM "MEM:"

/* ----------------------------------------------------------------
 * NAV.C
 * ---------------------------------------------------------------- */

#define LC_NAV_ERROR_1 "Minimal scale rate reached!"
#define LC_NAV_ERROR_2 "Maximal scale rate reached!"


#define LC_NAV_NORMAL_HEAD "GOTO SYSTEM (VIEW)"
#define LC_NAV_INPUT_COORD "Input system's INDEX"

/* ----------------------------------------------------------------
 * PATHWND.C
 * ---------------------------------------------------------------- */
#define LC_PATH_WND_HEAD "PATH"
#define LC_PATH_WND_SELECT "-SELECT"
#define LC_PATH_WND_CURRENT "<< CURRENT"
#define LC_PATH_WND_NEXT_JUMP "<< NEXT JUMP"
#define LC_PATH_WND_DANGER "DANGER"

/* ----------------------------------------------------------------
 * FINDER.C
 * ---------------------------------------------------------------- */

#define LC_FINDER_LOAD_CALC "Processing hyper-threads crossing:"
#define LC_FINDER_REALOC "Reallocating memory"

#define LC_FINDER_START_TEXT_1 "Input START system's INDEX"
#define LC_FINDER_START_TEXT_2 " Press [ENTER] to use current"
#define LC_FINDER_END_TEXT "Input DESTINATION system's INDEX."

#define LC_FINDER_ERROR_NOWAY "No possible path found"

/* ----------------------------------------------------------------
 * CARD.C
 * ---------------------------------------------------------------- */

/* F7 > ENTER */
#define LC_CARD_READY_TO_JUMP "CONFIRM JUMP FROM SA.%d TO SA.%d"
#define LC_CARD_JUMP_WND_HEAD "JUMP CONFIRMATION"

#define LC_CARD_JUMP_RESULT_HEAD "JUMP RESULT"
#define LC_CARD_JUMP_RESULT_TEXT "Welcome to SA.%d"

/* MENU WINDOWS */
#define LC_CARD_MENU_NEW_WND_HEAD "NEW GAME"
#define LC_CARD_MENU_SAVE_WND_HEAD "SAVE GAME"
#define LC_CARD_MENU_LOAD_WND_HEAD "LOAD GAME"

#define LC_CARD_MENU_SAVE_WND_TEXT "Input save file name"
#define LC_CARD_MENU_NEW_WND_TEXT "Enter captain's name:"
#define LC_CARD_MENU_SAVE_SUCCESS "Game saved!"
#define LC_CARD_MENU_SAVE_ERROR "Save Error"
#define LC_CARD_MENU_LOAD_ERROR "File not found"


/* ----------------------------------------------------------------
 * GAME DATA LOCALIZATION
 * ---------------------------------------------------------------- */

/* SHIP NAMES */
#define LC_GAME_SHIP_1 "Almighty's Boat"
#define LC_GAME_SHIP_2 "Betsy Boat"
#define LC_GAME_SHIP_3 "Old Imperial Trade Ship"
#define LC_GAME_SHIP_4 "Gae Bulg Ship"
#define LC_GAME_SHIP_5 "Nova Trade Carrier"
#define LC_GAME_SHIP_6 "Bulk Carrier" 

/* HYPER ENGINES */
#define LC_GAME_ENGINE_1 "Hyper Engine Mark I"
#define LC_GAME_ENGINE_2 "Hyper Engine Mark II"
#define LC_GAME_ENGINE_3 "Hyper Engine Mark III"
#define LC_GAME_ENGINE_4 "Hyper Engine [UMBRELLA]"

/* FACTIONS */
#define LC_GAME_FACTION_1 "Crescent and Star Union"
#define LC_GAME_FACTION_2 "Ireland-Mermaidian Confederation"
#define LC_GAME_FACTION_3 "Sentinel Coalition Peacemakers"
#define LC_GAME_FACTION_4 "Pirates"

/* SECTORS */
#define LC_GAME_SECTOR_1 "Dhat"
#define LC_GAME_SECTOR_2 "Medinat"
#define LC_GAME_SECTOR_3 "Ghabkar"
#define LC_GAME_SECTOR_4 "Buraq"
#define LC_GAME_SECTOR_5 "Ben Vara"
#define LC_GAME_SECTOR_6 "Killoch Vairan"
#define LC_GAME_SECTOR_7 "Cuchulainn"
#define LC_GAME_SECTOR_8 "Danter"
#define LC_GAME_SECTOR_9 "Coalsack"



/* ----------------------------------------------------------------
 * COMMON VALUES
 * ---------------------------------------------------------------- */

#define LC_GEN_TITLE_GSCARD "GSCARD 1.5"
#define LC_GEN_ERROR_INCORRECT_VALUE "Incorrect value!"
#define LC_GEN_ERROR_HEAD "ERROR"
#define LC_GEN_SUCCESS_HEAD "SUCCESS"

#endif

