[sdl]
autolock=false
fullscreen=false
fulldouble=false
fullresolution=original
windowresolution=original
output=surface
sensitivity=100
waitonerror=true
priority=higher,normal
mapperfile=mapper-jsdos.map
usescancodes=true
vsync=false

[dosbox]
machine=svga_s3

language=
captures=capture
memsize=16

#[cpu]
#core = auto
#cputype = pentium_iii
#cycles = max

[cpu]
core=dynamic
cputype=pentium_iii
cycles=407000

cycleup=10
cycledown=20

[mixer]
nosound=false
rate=44100

blocksize=1024
prebuffer=20

[render]
# frameskip: How many frames DOSBox skips before drawing one.
#    aspect: Do aspect correction, if your output method doesn't support scaling this can slow things down!.
#    scaler: Scaler used to enlarge/enhance low resolution modes.
#              If 'forced' is appended, then the scaler will be used even if the result might not be desired.
#            Possible values: none, normal2x, normal3x, advmame2x, advmame3x, advinterp2x, advinterp3x, hq2x, hq3x, 2xsai, super2xsai, supereagle, tv2x, tv3x, rgb2x, rgb3x, scan2x, scan3x.

frameskip=0
aspect=false
scaler=normal2x

[midi]
mpu401=none
mididevice=none

[sblaster]
sbtype=none

[gus]
#      gus: Enable the Gravis Ultrasound emulation.
gus=false

[speaker]
# pcspeaker: Enable PC-Speaker emulation.
#    pcrate: Sample rate of the PC-Speaker sound generation.
#            Possible values: 44100, 48000, 32000, 22050, 16000, 11025, 8000, 49716.
pcspeaker=true
pcrate=44100
tandy=off
tandyrate=44100
disney=false

[joystick]
joysticktype=none

[serial]
serial1=disabled
serial2=disabled
serial3=disabled
serial4=disabled

[dos]

xms=true
ems=true
umb=true
keyboardlayout=auto

[ipx]
ipx=false

[autoexec]
echo off
mount c .
c:
run.bat
