#ifndef _DATA_KEYS
#define _DATA_KEYS

#define ESC 0x1b
#define ENTER 0x0D
#define TAB 0x09
#define F1 0x3b
#define F2 0x3c
#define F3 0x3d
#define F4 0x3e
#define F5 0x3f
#define F6 0x40
#define F7 0x41
#define F8 0x42

#define UP 0x48
#define DWN 0x50
#define LFT 0x4b
#define RHT 0x4d
#define PUP 0x49
#define PDWN 0x51

#define KEY_D 0x64
#define KEY_D_UPPER 0x44

#define KEY_P     0x70
#define KEY_P_UPPER 0x50

#endif