char* ship_names[SHIP_COUNT] = {
    "Almighty's Boat", "Betsy Boat", "Old Imperial Trade Ship",
    "Gae Bulg Ship", "Nova Trade Carrier", "Bulk Carrier" 
};

int ship_tonnages[SHIP_COUNT] = {
    50, 80, 100, 150, 200, 400
};

char* hyper_names[HYPER_COUNT] = {
    "Hyper Engine Mark I", "Hyper Engine Mark II", 
    "Hyper Engine Mark III", "Hyper Engine [UMBRELLA]"
};

int hyper_fuel[HYPER_COUNT] = {
    10, 8, 5, 2
};

char* factions[4] = {
    "Serpent and Star Union", "Ireland-Mermaidian Confederation", "Sentinel Coalition Peacemakers", "Pirates"
};

char* sectors[9] = {
    "Dhat", "Medinat", "Ghabkar", "Buraq", "Ben Vara", "Killoch Vairan", "Cuchulainn", "Danter", "Coalsack"
};